# Generated by Django 5.2 on 2025-05-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_livro_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='capa',
        ),
    ]
