# Generated by Django 5.2 on 2025-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_editora_cidade_editora_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.CharField(blank=True, help_text='Passage ID', max_length=255, null=True, unique=True, verbose_name='passage_id'),
        ),
    ]
